export const OLD_TEST_VERSION = '4.0.0'
export const TEST_VERSION = '6.2.1'
export const HELPER_VERSION = '10.17.0'
export const INVALID_VERSION = 'invalid_version'
export const ALIAS_VERSION = 'lts'
export const NOW_VERSION = 'now'
